// Configuration partagée des outils et du system prompt de l'agent.
// Utilisé à la fois par /chat (agent.functions.ts) et par /dashboard+/agent (agent-runs.functions.ts)
// pour garantir un comportement identique quel que soit le point d'entrée.

export const AGENT_SYSTEM_PROMPT = `Tu es **JurisAI**, copilote juridique transverse pour cabinets et entreprises (RH, commercial, sociétés, RGPD, fiscal, contentieux, administratif).

LOGIQUE OBLIGATOIRE : Comprendre → Sourcer → Proposer → Préparer → Valider → Exécuter → Archiver → Suivre → Alerter.

RÈGLES STRICTES :
1. Pour toute affirmation juridique : appelle search_law et cite via [source:N]. Pas de source = refus motivé.
2. Pour tout document à risque (licenciement, mise en demeure, transaction, contentieux, dépôt légal) : passe par request_validation, jamais d'exécution directe.
3. Toute action significative sur un dossier doit produire une trace (les outils log_timeline automatiquement).
4. Si la demande est hors juridique, redirige poliment.
5. Réponds en français, ton professionnel, structure claire.
6. Tu ne donnes jamais de consultation se substituant à un avocat. Tes réponses sont informatives et ne constituent pas un avis juridique.

HIÉRARCHIE DES SOURCES — structure ta réponse en respectant la hiérarchie normative :
1. **Textes législatifs** (Code du travail, lois, décrets) — toujours citer en premier.
2. **Convention collective / accord** applicable — si pertinent au cas.
3. **Jurisprudence** — pour illustrer l'interprétation des textes.
Ne cite JAMAIS la jurisprudence seule sans le texte de loi qu'elle interprète.

Date courante : 2026.`;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const AGENT_TOOLS: any[] = [
  { type: "function", function: { name: "search_law", description: "RAG dans les sources juridiques officielles. À appeler avant toute affirmation.", parameters: { type: "object", properties: { query: { type: "string" } }, required: ["query"] } } },
  { type: "function", function: { name: "dossier_context", description: "Récupère le contexte d'un dossier (timeline, tâches, risques, échéances).", parameters: { type: "object", properties: { dossier_id: { type: "string" } }, required: ["dossier_id"] } } },
  { type: "function", function: { name: "identify_risk", description: "Enregistre un risque juridique sur un dossier.", parameters: { type: "object", properties: { dossier_id: { type: "string" }, title: { type: "string" }, severity: { type: "string", enum: ["low", "medium", "high", "critical"] }, legal_basis: { type: "string" }, description: { type: "string" } }, required: ["dossier_id", "title", "severity"] } } },
  { type: "function", function: { name: "propose_document", description: "Initie une session de génération de document. Pour docs sensibles → demande de validation auto.", parameters: { type: "object", properties: { dossier_id: { type: "string" }, doc_type: { type: "string" }, domain: { type: "string" }, params: { type: "object" } }, required: ["dossier_id", "doc_type"] } } },
  { type: "function", function: { name: "request_validation", description: "Crée une demande de validation hiérarchique avant exécution d'une action engageante.", parameters: { type: "object", properties: { dossier_id: { type: "string" }, action_type: { type: "string" }, reason: { type: "string" }, payload: { type: "object" } }, required: ["dossier_id", "action_type"] } } },
  { type: "function", function: { name: "schedule_reminder", description: "Programme un rappel.", parameters: { type: "object", properties: { dossier_id: { type: "string" }, title: { type: "string" }, remind_at: { type: "string" }, channel: { type: "string", enum: ["in_app", "email"] } }, required: ["title", "remind_at"] } } },
  { type: "function", function: { name: "create_task", description: "Crée une tâche dans un dossier.", parameters: { type: "object", properties: { dossier_id: { type: "string" }, title: { type: "string" }, priority: { type: "string", enum: ["low", "normal", "high", "urgent"] }, due_date: { type: "string" } }, required: ["dossier_id", "title"] } } },
  { type: "function", function: { name: "update_task", description: "Met à jour le statut, la priorité ou le titre d'une tâche existante.", parameters: { type: "object", properties: { task_id: { type: "string" }, dossier_id: { type: "string" }, status: { type: "string", enum: ["todo", "in_progress", "done", "cancelled"] }, priority: { type: "string", enum: ["low", "normal", "high", "urgent"] }, title: { type: "string" } }, required: ["task_id", "dossier_id"] } } },
  { type: "function", function: { name: "create_deadline", description: "Crée une échéance.", parameters: { type: "object", properties: { dossier_id: { type: "string" }, title: { type: "string" }, due_date: { type: "string" } }, required: ["dossier_id", "title", "due_date"] } } },
  { type: "function", function: { name: "search_dossier", description: "Recherche dans les dossiers du tenant par titre ou description.", parameters: { type: "object", properties: { query: { type: "string" }, limit: { type: "number" } }, required: ["query"] } } },
  { type: "function", function: { name: "create_dossier", description: "Crée un nouveau dossier juridique pour le tenant.", parameters: { type: "object", properties: { title: { type: "string" }, category: { type: "string" }, description: { type: "string" }, client_id: { type: "string" }, risk_level: { type: "string", enum: ["low", "medium", "high", "critical"] } }, required: ["title"] } } },
  { type: "function", function: { name: "start_workflow", description: "Instancie une procédure (workflow) depuis sa définition.", parameters: { type: "object", properties: { definition_id: { type: "string" }, definition_slug: { type: "string" }, title: { type: "string" }, dossier_id: { type: "string" }, client_id: { type: "string" }, context: { type: "object" } } } } },
  { type: "function", function: { name: "analyze_document", description: "Analyse un document (résumé, type, risques, clauses manquantes).", parameters: { type: "object", properties: { document_id: { type: "string" }, dossier_id: { type: "string" } }, required: ["document_id"] } } },
  { type: "function", function: { name: "generate_report", description: "Génère un rapport markdown synthétisant un dossier.", parameters: { type: "object", properties: { dossier_id: { type: "string" }, report_type: { type: "string" } }, required: ["dossier_id"] } } },
  { type: "function", function: { name: "generate_workflow", description: "Génère une nouvelle procédure (workflow) juridique à partir d'une demande en langage naturel.", parameters: { type: "object", properties: { prompt: { type: "string", description: "Description en langage naturel de la procédure à générer." }, category: { type: "string", description: "Domaine juridique : social, commercial, rgpd, fiscal, contentieux, societes, administratif." } }, required: ["prompt"] } } },
  { type: "function", function: { name: "run_workflow_step", description: "Exécute l'étape courante d'un workflow déjà instancié.", parameters: { type: "object", properties: { instance_id: { type: "string" }, step_index: { type: "number" }, notes: { type: "string" } }, required: ["instance_id", "step_index"] } } },
  { type: "function", function: { name: "compare_contracts", description: "Compare deux documents contractuels (deux versions, ou contrat vs modèle de référence). Retourne un diff sémantique : clauses ajoutées/supprimées/modifiées, clauses risquées en droit français, score de risque global et recommandations. À utiliser dès que l'utilisateur demande de comparer, confronter, ou auditer la différence entre deux contrats.", parameters: { type: "object", properties: { doc_a_id: { type: "string", description: "UUID du document A" }, doc_b_id: { type: "string", description: "UUID du document B" } }, required: ["doc_a_id", "doc_b_id"] } } },
  { type: "function", function: { name: "calculate_indemnity", description: "Calcule les indemnités de rupture (licenciement, rupture conventionnelle, retraite) en comparant légal vs conventionnel (principe de faveur). Retourne le détail de chaque composante avec références légales.", parameters: { type: "object", properties: { salaire_mensuel_brut: { type: "number", description: "Salaire mensuel brut de référence en euros" }, salaire_moyen_12m: { type: "number", description: "Moyenne des 12 derniers mois (optionnel)" }, salaire_moyen_3m: { type: "number", description: "Moyenne des 3 derniers mois avec primes proratisées (optionnel)" }, anciennete_mois: { type: "number", description: "Ancienneté totale en mois" }, motif: { type: "string", enum: ["licenciement_cause_reelle", "licenciement_faute_grave", "licenciement_faute_lourde", "licenciement_eco", "rupture_conventionnelle", "mise_retraite", "depart_retraite", "licenciement_inaptitude_pro", "licenciement_inaptitude_non_pro"], description: "Motif de la rupture" }, idcc: { type: "string", description: "Code IDCC de la convention collective (ex: 1486 pour Syntec)" }, categorie: { type: "string", description: "Catégorie professionnelle : cadre, non-cadre, ETAM..." }, taille_entreprise: { type: "string", enum: ["standard", "small"], description: "standard (≥11 salariés) ou small (<11)" }, date_effet: { type: "string", description: "Date du fait générateur (YYYY-MM-DD)" }, jours_conges_non_pris: { type: "number", description: "Nombre de jours de congés non pris" }, dossier_id: { type: "string", description: "ID du dossier lié (optionnel)" } }, required: ["salaire_mensuel_brut", "anciennete_mois", "motif"] } } },
];
