/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated/workflows'
import { Route as AuthenticatedVeilleRouteImport } from './routes/_authenticated/veille'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLinksRouteImport } from './routes/_authenticated/links'
import { Route as AuthenticatedDossiersRouteImport } from './routes/_authenticated/dossiers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalysesRouteImport } from './routes/_authenticated/analyses'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents.index'
import { Route as AuthenticatedWorkflowsIdRouteImport } from './routes/_authenticated/workflows_.$id'
import { Route as AuthenticatedDossiersIdRouteImport } from './routes/_authenticated/dossiers.$id'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents.$id'
import { Route as AuthenticatedAnalysesIdRouteImport } from './routes/_authenticated/analyses.$id'
import { Route as AuthenticatedAdminWorkflowGeneratorRouteImport } from './routes/_authenticated/admin.workflow-generator'
import { Route as AuthenticatedAdminUsageRouteImport } from './routes/_authenticated/admin.usage'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated/admin.tenants'
import { Route as AuthenticatedAdminServerErrorsRouteImport } from './routes/_authenticated/admin.server-errors'
import { Route as AuthenticatedAdminRagQualityRouteImport } from './routes/_authenticated/admin.rag-quality'
import { Route as AuthenticatedAdminLegalSourcesRouteImport } from './routes/_authenticated/admin.legal-sources'
import { Route as AuthenticatedAdminDataQualityRouteImport } from './routes/_authenticated/admin.data-quality'
import { Route as AuthenticatedAdminConnectorsRouteImport } from './routes/_authenticated/admin.connectors'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as ApiPublicV1MeRouteImport } from './routes/api/public/v1.me'
import { Route as ApiPublicV1DossiersRouteImport } from './routes/api/public/v1.dossiers'
import { Route as ApiPublicV1DeadlinesRouteImport } from './routes/api/public/v1.deadlines'
import { Route as ApiPublicV1ClientsRouteImport } from './routes/api/public/v1.clients'
import { Route as ApiPublicHooksOrchestratorTickRouteImport } from './routes/api/public/hooks/orchestrator-tick'
import { Route as ApiPublicHooksDispatchRemindersRouteImport } from './routes/api/public/hooks/dispatch-reminders'
import { Route as ApiPublicHooksDigestRouteImport } from './routes/api/public/hooks/digest'
import { Route as ApiPublicHooksContractDeadlinesRouteImport } from './routes/api/public/hooks/contract-deadlines'
import { Route as ApiPublicCalendarTokenRouteImport } from './routes/api/public/calendar.$token'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVeilleRoute = AuthenticatedVeilleRouteImport.update({
  id: '/veille',
  path: '/veille',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLinksRoute = AuthenticatedLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDossiersRoute = AuthenticatedDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalysesRoute = AuthenticatedAnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowsIdRoute =
  AuthenticatedWorkflowsIdRouteImport.update({
    id: '/workflows_/$id',
    path: '/workflows/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDossiersIdRoute = AuthenticatedDossiersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDossiersRoute,
} as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/documents/$id',
    path: '/documents/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalysesIdRoute = AuthenticatedAnalysesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAnalysesRoute,
} as any)
const AuthenticatedAdminWorkflowGeneratorRoute =
  AuthenticatedAdminWorkflowGeneratorRouteImport.update({
    id: '/admin/workflow-generator',
    path: '/admin/workflow-generator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsageRoute = AuthenticatedAdminUsageRouteImport.update({
  id: '/admin/usage',
  path: '/admin/usage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/admin/tenants',
    path: '/admin/tenants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminServerErrorsRoute =
  AuthenticatedAdminServerErrorsRouteImport.update({
    id: '/admin/server-errors',
    path: '/admin/server-errors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRagQualityRoute =
  AuthenticatedAdminRagQualityRouteImport.update({
    id: '/admin/rag-quality',
    path: '/admin/rag-quality',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLegalSourcesRoute =
  AuthenticatedAdminLegalSourcesRouteImport.update({
    id: '/admin/legal-sources',
    path: '/admin/legal-sources',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDataQualityRoute =
  AuthenticatedAdminDataQualityRouteImport.update({
    id: '/admin/data-quality',
    path: '/admin/data-quality',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminConnectorsRoute =
  AuthenticatedAdminConnectorsRouteImport.update({
    id: '/admin/connectors',
    path: '/admin/connectors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicV1MeRoute = ApiPublicV1MeRouteImport.update({
  id: '/api/public/v1/me',
  path: '/api/public/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1DossiersRoute = ApiPublicV1DossiersRouteImport.update({
  id: '/api/public/v1/dossiers',
  path: '/api/public/v1/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1DeadlinesRoute = ApiPublicV1DeadlinesRouteImport.update({
  id: '/api/public/v1/deadlines',
  path: '/api/public/v1/deadlines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ClientsRoute = ApiPublicV1ClientsRouteImport.update({
  id: '/api/public/v1/clients',
  path: '/api/public/v1/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksOrchestratorTickRoute =
  ApiPublicHooksOrchestratorTickRouteImport.update({
    id: '/api/public/hooks/orchestrator-tick',
    path: '/api/public/hooks/orchestrator-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchRemindersRoute =
  ApiPublicHooksDispatchRemindersRouteImport.update({
    id: '/api/public/hooks/dispatch-reminders',
    path: '/api/public/hooks/dispatch-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDigestRoute = ApiPublicHooksDigestRouteImport.update({
  id: '/api/public/hooks/digest',
  path: '/api/public/hooks/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksContractDeadlinesRoute =
  ApiPublicHooksContractDeadlinesRouteImport.update({
    id: '/api/public/hooks/contract-deadlines',
    path: '/api/public/hooks/contract-deadlines',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCalendarTokenRoute = ApiPublicCalendarTokenRouteImport.update({
  id: '/api/public/calendar/$token',
  path: '/api/public/calendar/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/analyses': typeof AuthenticatedAnalysesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dossiers': typeof AuthenticatedDossiersRouteWithChildren
  '/links': typeof AuthenticatedLinksRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/veille': typeof AuthenticatedVeilleRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/connectors': typeof AuthenticatedAdminConnectorsRoute
  '/admin/data-quality': typeof AuthenticatedAdminDataQualityRoute
  '/admin/legal-sources': typeof AuthenticatedAdminLegalSourcesRoute
  '/admin/rag-quality': typeof AuthenticatedAdminRagQualityRoute
  '/admin/server-errors': typeof AuthenticatedAdminServerErrorsRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/workflow-generator': typeof AuthenticatedAdminWorkflowGeneratorRoute
  '/analyses/$id': typeof AuthenticatedAnalysesIdRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/dossiers/$id': typeof AuthenticatedDossiersIdRoute
  '/workflows/$id': typeof AuthenticatedWorkflowsIdRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/hooks/contract-deadlines': typeof ApiPublicHooksContractDeadlinesRoute
  '/api/public/hooks/digest': typeof ApiPublicHooksDigestRoute
  '/api/public/hooks/dispatch-reminders': typeof ApiPublicHooksDispatchRemindersRoute
  '/api/public/hooks/orchestrator-tick': typeof ApiPublicHooksOrchestratorTickRoute
  '/api/public/v1/clients': typeof ApiPublicV1ClientsRoute
  '/api/public/v1/deadlines': typeof ApiPublicV1DeadlinesRoute
  '/api/public/v1/dossiers': typeof ApiPublicV1DossiersRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/analyses': typeof AuthenticatedAnalysesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dossiers': typeof AuthenticatedDossiersRouteWithChildren
  '/links': typeof AuthenticatedLinksRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/veille': typeof AuthenticatedVeilleRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/connectors': typeof AuthenticatedAdminConnectorsRoute
  '/admin/data-quality': typeof AuthenticatedAdminDataQualityRoute
  '/admin/legal-sources': typeof AuthenticatedAdminLegalSourcesRoute
  '/admin/rag-quality': typeof AuthenticatedAdminRagQualityRoute
  '/admin/server-errors': typeof AuthenticatedAdminServerErrorsRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/workflow-generator': typeof AuthenticatedAdminWorkflowGeneratorRoute
  '/analyses/$id': typeof AuthenticatedAnalysesIdRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/dossiers/$id': typeof AuthenticatedDossiersIdRoute
  '/workflows/$id': typeof AuthenticatedWorkflowsIdRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/hooks/contract-deadlines': typeof ApiPublicHooksContractDeadlinesRoute
  '/api/public/hooks/digest': typeof ApiPublicHooksDigestRoute
  '/api/public/hooks/dispatch-reminders': typeof ApiPublicHooksDispatchRemindersRoute
  '/api/public/hooks/orchestrator-tick': typeof ApiPublicHooksOrchestratorTickRoute
  '/api/public/v1/clients': typeof ApiPublicV1ClientsRoute
  '/api/public/v1/deadlines': typeof ApiPublicV1DeadlinesRoute
  '/api/public/v1/dossiers': typeof ApiPublicV1DossiersRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/analyses': typeof AuthenticatedAnalysesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dossiers': typeof AuthenticatedDossiersRouteWithChildren
  '/_authenticated/links': typeof AuthenticatedLinksRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/_authenticated/veille': typeof AuthenticatedVeilleRoute
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/connectors': typeof AuthenticatedAdminConnectorsRoute
  '/_authenticated/admin/data-quality': typeof AuthenticatedAdminDataQualityRoute
  '/_authenticated/admin/legal-sources': typeof AuthenticatedAdminLegalSourcesRoute
  '/_authenticated/admin/rag-quality': typeof AuthenticatedAdminRagQualityRoute
  '/_authenticated/admin/server-errors': typeof AuthenticatedAdminServerErrorsRoute
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/_authenticated/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/_authenticated/admin/workflow-generator': typeof AuthenticatedAdminWorkflowGeneratorRoute
  '/_authenticated/analyses/$id': typeof AuthenticatedAnalysesIdRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/dossiers/$id': typeof AuthenticatedDossiersIdRoute
  '/_authenticated/workflows_/$id': typeof AuthenticatedWorkflowsIdRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/hooks/contract-deadlines': typeof ApiPublicHooksContractDeadlinesRoute
  '/api/public/hooks/digest': typeof ApiPublicHooksDigestRoute
  '/api/public/hooks/dispatch-reminders': typeof ApiPublicHooksDispatchRemindersRoute
  '/api/public/hooks/orchestrator-tick': typeof ApiPublicHooksOrchestratorTickRoute
  '/api/public/v1/clients': typeof ApiPublicV1ClientsRoute
  '/api/public/v1/deadlines': typeof ApiPublicV1DeadlinesRoute
  '/api/public/v1/dossiers': typeof ApiPublicV1DossiersRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/cgu'
    | '/confidentialite'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/agent'
    | '/analyses'
    | '/dashboard'
    | '/dossiers'
    | '/links'
    | '/notifications'
    | '/scan'
    | '/settings'
    | '/team'
    | '/templates'
    | '/upgrade'
    | '/veille'
    | '/workflows'
    | '/admin/audit'
    | '/admin/connectors'
    | '/admin/data-quality'
    | '/admin/legal-sources'
    | '/admin/rag-quality'
    | '/admin/server-errors'
    | '/admin/tenants'
    | '/admin/usage'
    | '/admin/workflow-generator'
    | '/analyses/$id'
    | '/documents/$id'
    | '/dossiers/$id'
    | '/workflows/$id'
    | '/documents/'
    | '/api/public/calendar/$token'
    | '/api/public/hooks/contract-deadlines'
    | '/api/public/hooks/digest'
    | '/api/public/hooks/dispatch-reminders'
    | '/api/public/hooks/orchestrator-tick'
    | '/api/public/v1/clients'
    | '/api/public/v1/deadlines'
    | '/api/public/v1/dossiers'
    | '/api/public/v1/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/cgu'
    | '/confidentialite'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/agent'
    | '/analyses'
    | '/dashboard'
    | '/dossiers'
    | '/links'
    | '/notifications'
    | '/scan'
    | '/settings'
    | '/team'
    | '/templates'
    | '/upgrade'
    | '/veille'
    | '/workflows'
    | '/admin/audit'
    | '/admin/connectors'
    | '/admin/data-quality'
    | '/admin/legal-sources'
    | '/admin/rag-quality'
    | '/admin/server-errors'
    | '/admin/tenants'
    | '/admin/usage'
    | '/admin/workflow-generator'
    | '/analyses/$id'
    | '/documents/$id'
    | '/dossiers/$id'
    | '/workflows/$id'
    | '/documents'
    | '/api/public/calendar/$token'
    | '/api/public/hooks/contract-deadlines'
    | '/api/public/hooks/digest'
    | '/api/public/hooks/dispatch-reminders'
    | '/api/public/hooks/orchestrator-tick'
    | '/api/public/v1/clients'
    | '/api/public/v1/deadlines'
    | '/api/public/v1/dossiers'
    | '/api/public/v1/me'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invitation'
    | '/cgu'
    | '/confidentialite'
    | '/forgot-password'
    | '/login'
    | '/mentions-legales'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/agent'
    | '/_authenticated/analyses'
    | '/_authenticated/dashboard'
    | '/_authenticated/dossiers'
    | '/_authenticated/links'
    | '/_authenticated/notifications'
    | '/_authenticated/scan'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/templates'
    | '/_authenticated/upgrade'
    | '/_authenticated/veille'
    | '/_authenticated/workflows'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/connectors'
    | '/_authenticated/admin/data-quality'
    | '/_authenticated/admin/legal-sources'
    | '/_authenticated/admin/rag-quality'
    | '/_authenticated/admin/server-errors'
    | '/_authenticated/admin/tenants'
    | '/_authenticated/admin/usage'
    | '/_authenticated/admin/workflow-generator'
    | '/_authenticated/analyses/$id'
    | '/_authenticated/documents/$id'
    | '/_authenticated/dossiers/$id'
    | '/_authenticated/workflows_/$id'
    | '/_authenticated/documents/'
    | '/api/public/calendar/$token'
    | '/api/public/hooks/contract-deadlines'
    | '/api/public/hooks/digest'
    | '/api/public/hooks/dispatch-reminders'
    | '/api/public/hooks/orchestrator-tick'
    | '/api/public/v1/clients'
    | '/api/public/v1/deadlines'
    | '/api/public/v1/dossiers'
    | '/api/public/v1/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  CguRoute: typeof CguRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPublicCalendarTokenRoute: typeof ApiPublicCalendarTokenRoute
  ApiPublicHooksContractDeadlinesRoute: typeof ApiPublicHooksContractDeadlinesRoute
  ApiPublicHooksDigestRoute: typeof ApiPublicHooksDigestRoute
  ApiPublicHooksDispatchRemindersRoute: typeof ApiPublicHooksDispatchRemindersRoute
  ApiPublicHooksOrchestratorTickRoute: typeof ApiPublicHooksOrchestratorTickRoute
  ApiPublicV1ClientsRoute: typeof ApiPublicV1ClientsRoute
  ApiPublicV1DeadlinesRoute: typeof ApiPublicV1DeadlinesRoute
  ApiPublicV1DossiersRoute: typeof ApiPublicV1DossiersRoute
  ApiPublicV1MeRoute: typeof ApiPublicV1MeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/veille': {
      id: '/_authenticated/veille'
      path: '/veille'
      fullPath: '/veille'
      preLoaderRoute: typeof AuthenticatedVeilleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/links': {
      id: '/_authenticated/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AuthenticatedLinksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dossiers': {
      id: '/_authenticated/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof AuthenticatedDossiersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyses': {
      id: '/_authenticated/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AuthenticatedAnalysesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows_/$id': {
      id: '/_authenticated/workflows_/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof AuthenticatedWorkflowsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dossiers/$id': {
      id: '/_authenticated/dossiers/$id'
      path: '/$id'
      fullPath: '/dossiers/$id'
      preLoaderRoute: typeof AuthenticatedDossiersIdRouteImport
      parentRoute: typeof AuthenticatedDossiersRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyses/$id': {
      id: '/_authenticated/analyses/$id'
      path: '/$id'
      fullPath: '/analyses/$id'
      preLoaderRoute: typeof AuthenticatedAnalysesIdRouteImport
      parentRoute: typeof AuthenticatedAnalysesRoute
    }
    '/_authenticated/admin/workflow-generator': {
      id: '/_authenticated/admin/workflow-generator'
      path: '/admin/workflow-generator'
      fullPath: '/admin/workflow-generator'
      preLoaderRoute: typeof AuthenticatedAdminWorkflowGeneratorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usage': {
      id: '/_authenticated/admin/usage'
      path: '/admin/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthenticatedAdminUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/server-errors': {
      id: '/_authenticated/admin/server-errors'
      path: '/admin/server-errors'
      fullPath: '/admin/server-errors'
      preLoaderRoute: typeof AuthenticatedAdminServerErrorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/rag-quality': {
      id: '/_authenticated/admin/rag-quality'
      path: '/admin/rag-quality'
      fullPath: '/admin/rag-quality'
      preLoaderRoute: typeof AuthenticatedAdminRagQualityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/legal-sources': {
      id: '/_authenticated/admin/legal-sources'
      path: '/admin/legal-sources'
      fullPath: '/admin/legal-sources'
      preLoaderRoute: typeof AuthenticatedAdminLegalSourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/data-quality': {
      id: '/_authenticated/admin/data-quality'
      path: '/admin/data-quality'
      fullPath: '/admin/data-quality'
      preLoaderRoute: typeof AuthenticatedAdminDataQualityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/connectors': {
      id: '/_authenticated/admin/connectors'
      path: '/admin/connectors'
      fullPath: '/admin/connectors'
      preLoaderRoute: typeof AuthenticatedAdminConnectorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/v1/me': {
      id: '/api/public/v1/me'
      path: '/api/public/v1/me'
      fullPath: '/api/public/v1/me'
      preLoaderRoute: typeof ApiPublicV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/dossiers': {
      id: '/api/public/v1/dossiers'
      path: '/api/public/v1/dossiers'
      fullPath: '/api/public/v1/dossiers'
      preLoaderRoute: typeof ApiPublicV1DossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/deadlines': {
      id: '/api/public/v1/deadlines'
      path: '/api/public/v1/deadlines'
      fullPath: '/api/public/v1/deadlines'
      preLoaderRoute: typeof ApiPublicV1DeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/clients': {
      id: '/api/public/v1/clients'
      path: '/api/public/v1/clients'
      fullPath: '/api/public/v1/clients'
      preLoaderRoute: typeof ApiPublicV1ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/orchestrator-tick': {
      id: '/api/public/hooks/orchestrator-tick'
      path: '/api/public/hooks/orchestrator-tick'
      fullPath: '/api/public/hooks/orchestrator-tick'
      preLoaderRoute: typeof ApiPublicHooksOrchestratorTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-reminders': {
      id: '/api/public/hooks/dispatch-reminders'
      path: '/api/public/hooks/dispatch-reminders'
      fullPath: '/api/public/hooks/dispatch-reminders'
      preLoaderRoute: typeof ApiPublicHooksDispatchRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/digest': {
      id: '/api/public/hooks/digest'
      path: '/api/public/hooks/digest'
      fullPath: '/api/public/hooks/digest'
      preLoaderRoute: typeof ApiPublicHooksDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/contract-deadlines': {
      id: '/api/public/hooks/contract-deadlines'
      path: '/api/public/hooks/contract-deadlines'
      fullPath: '/api/public/hooks/contract-deadlines'
      preLoaderRoute: typeof ApiPublicHooksContractDeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/$token': {
      id: '/api/public/calendar/$token'
      path: '/api/public/calendar/$token'
      fullPath: '/api/public/calendar/$token'
      preLoaderRoute: typeof ApiPublicCalendarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAnalysesRouteChildren {
  AuthenticatedAnalysesIdRoute: typeof AuthenticatedAnalysesIdRoute
}

const AuthenticatedAnalysesRouteChildren: AuthenticatedAnalysesRouteChildren = {
  AuthenticatedAnalysesIdRoute: AuthenticatedAnalysesIdRoute,
}

const AuthenticatedAnalysesRouteWithChildren =
  AuthenticatedAnalysesRoute._addFileChildren(
    AuthenticatedAnalysesRouteChildren,
  )

interface AuthenticatedDossiersRouteChildren {
  AuthenticatedDossiersIdRoute: typeof AuthenticatedDossiersIdRoute
}

const AuthenticatedDossiersRouteChildren: AuthenticatedDossiersRouteChildren = {
  AuthenticatedDossiersIdRoute: AuthenticatedDossiersIdRoute,
}

const AuthenticatedDossiersRouteWithChildren =
  AuthenticatedDossiersRoute._addFileChildren(
    AuthenticatedDossiersRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedAnalysesRoute: typeof AuthenticatedAnalysesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDossiersRoute: typeof AuthenticatedDossiersRouteWithChildren
  AuthenticatedLinksRoute: typeof AuthenticatedLinksRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
  AuthenticatedVeilleRoute: typeof AuthenticatedVeilleRoute
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminConnectorsRoute: typeof AuthenticatedAdminConnectorsRoute
  AuthenticatedAdminDataQualityRoute: typeof AuthenticatedAdminDataQualityRoute
  AuthenticatedAdminLegalSourcesRoute: typeof AuthenticatedAdminLegalSourcesRoute
  AuthenticatedAdminRagQualityRoute: typeof AuthenticatedAdminRagQualityRoute
  AuthenticatedAdminServerErrorsRoute: typeof AuthenticatedAdminServerErrorsRoute
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRoute
  AuthenticatedAdminUsageRoute: typeof AuthenticatedAdminUsageRoute
  AuthenticatedAdminWorkflowGeneratorRoute: typeof AuthenticatedAdminWorkflowGeneratorRoute
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
  AuthenticatedWorkflowsIdRoute: typeof AuthenticatedWorkflowsIdRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedAnalysesRoute: AuthenticatedAnalysesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDossiersRoute: AuthenticatedDossiersRouteWithChildren,
  AuthenticatedLinksRoute: AuthenticatedLinksRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
  AuthenticatedVeilleRoute: AuthenticatedVeilleRoute,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminConnectorsRoute: AuthenticatedAdminConnectorsRoute,
  AuthenticatedAdminDataQualityRoute: AuthenticatedAdminDataQualityRoute,
  AuthenticatedAdminLegalSourcesRoute: AuthenticatedAdminLegalSourcesRoute,
  AuthenticatedAdminRagQualityRoute: AuthenticatedAdminRagQualityRoute,
  AuthenticatedAdminServerErrorsRoute: AuthenticatedAdminServerErrorsRoute,
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRoute,
  AuthenticatedAdminUsageRoute: AuthenticatedAdminUsageRoute,
  AuthenticatedAdminWorkflowGeneratorRoute:
    AuthenticatedAdminWorkflowGeneratorRoute,
  AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
  AuthenticatedWorkflowsIdRoute: AuthenticatedWorkflowsIdRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  CguRoute: CguRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPublicCalendarTokenRoute: ApiPublicCalendarTokenRoute,
  ApiPublicHooksContractDeadlinesRoute: ApiPublicHooksContractDeadlinesRoute,
  ApiPublicHooksDigestRoute: ApiPublicHooksDigestRoute,
  ApiPublicHooksDispatchRemindersRoute: ApiPublicHooksDispatchRemindersRoute,
  ApiPublicHooksOrchestratorTickRoute: ApiPublicHooksOrchestratorTickRoute,
  ApiPublicV1ClientsRoute: ApiPublicV1ClientsRoute,
  ApiPublicV1DeadlinesRoute: ApiPublicV1DeadlinesRoute,
  ApiPublicV1DossiersRoute: ApiPublicV1DossiersRoute,
  ApiPublicV1MeRoute: ApiPublicV1MeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
