DO $$
DECLARE
  templates jsonb := '[
    {"slug":"rgpd-registre-traitement","name":"Registre des activités de traitement (RGPD art. 30)","description":"Fiche de registre RGPD","category":"rgpd","risk_level":"high","icon":"ShieldCheck",
     "body":"<h1>Registre des activités de traitement</h1><p><strong>Responsable :</strong> {{responsable}}</p><p><strong>Nom du traitement :</strong> {{nom_traitement}}</p><p><strong>Finalité :</strong> {{finalite}}</p><p><strong>Base légale :</strong> {{base_legale}}</p><p><strong>Personnes :</strong> {{personnes_concernees}}</p><p><strong>Données :</strong> {{categories_donnees}}</p><p><strong>Destinataires :</strong> {{destinataires}}</p><p><strong>Conservation :</strong> {{duree_conservation}}</p><p><strong>Sécurité :</strong> {{mesures_securite}}</p>",
     "variables":[{"key":"responsable","label":"Responsable","type":"text","required":true},{"key":"nom_traitement","label":"Nom traitement","type":"text","required":true},{"key":"finalite","label":"Finalité","type":"textarea","required":true},{"key":"base_legale","label":"Base légale","type":"select","required":true,"options":["Consentement","Contrat","Obligation légale","Intérêt légitime"]},{"key":"personnes_concernees","label":"Personnes","type":"text","required":true},{"key":"categories_donnees","label":"Données","type":"textarea","required":true},{"key":"destinataires","label":"Destinataires","type":"textarea","required":true},{"key":"duree_conservation","label":"Conservation","type":"text","required":true},{"key":"mesures_securite","label":"Sécurité","type":"textarea","required":true}],
     "legal_basis":[{"label":"RGPD art. 30"}]},
    {"slug":"rgpd-reponse-droit-acces","name":"Réponse à une demande de droit d acces","description":"Réponse RGPD art. 15","category":"rgpd","risk_level":"high","icon":"Mail",
     "body":"<p>{{nom_demandeur}}</p><p>Objet : droit d acces</p><p>Demande du {{date_demande}}. Données : {{contenu_donnees}}. Finalités : {{finalites}}. {{signataire}}</p>",
     "variables":[{"key":"nom_demandeur","label":"Demandeur","type":"text","required":true},{"key":"date_demande","label":"Date","type":"date","required":true},{"key":"contenu_donnees","label":"Données","type":"textarea","required":true},{"key":"finalites","label":"Finalités","type":"textarea","required":true},{"key":"signataire","label":"Signataire","type":"text","required":true}],
     "legal_basis":[{"label":"RGPD art. 15"}]},
    {"slug":"cgv-prestation-services","name":"CGV - Prestations de services","description":"CGV B2B","category":"commercial","risk_level":"high","icon":"FileSignature",
     "body":"<h1>CGV</h1><p>{{raison_sociale}}, {{forme_juridique}}, capital {{capital}} euros, RCS {{rcs}}, siège {{siege}}.</p><h2>Art.1 Objet</h2><p>{{type_prestation}}</p><h2>Art.2 Paiement</h2><p>{{delai_paiement}} jours. Pénalités BCE+10pts + 40 euros.</p><h2>Art.3 Durée</h2><p>{{duree_contrat}}</p><h2>Art.4 Responsabilité</h2><p>Plafond : {{plafond_responsabilite}}</p><h2>Art.5 Droit</h2><p>Tribunal {{tribunal_competent}}.</p>",
     "variables":[{"key":"raison_sociale","label":"Raison sociale","type":"text","required":true},{"key":"forme_juridique","label":"Forme","type":"select","options":["SAS","SARL","SA","SASU","EURL","SCI"],"required":true},{"key":"capital","label":"Capital","type":"number","required":true},{"key":"rcs","label":"RCS","type":"text","required":true},{"key":"siege","label":"Siège","type":"text","required":true},{"key":"type_prestation","label":"Prestation","type":"text","required":true},{"key":"delai_paiement","label":"Délai (jours)","type":"number","required":true},{"key":"duree_contrat","label":"Durée","type":"text","required":true},{"key":"plafond_responsabilite","label":"Plafond","type":"text","required":true},{"key":"tribunal_competent","label":"Tribunal","type":"text","required":true}],
     "legal_basis":[{"label":"C. com. L441-10"}]},
    {"slug":"mise-en-demeure-payer-commercial","name":"Mise en demeure de payer (B2B)","description":"Facture impayée B2B","category":"commercial","risk_level":"medium","icon":"AlertTriangle",
     "body":"<p>{{nom_debiteur}}<br/>{{adresse_debiteur}}</p><p>LRAR - {{date}}</p><p><strong>Mise en demeure de payer</strong></p><p>Facture n° {{numero_facture}} du {{date_facture}} : {{montant}} euros TTC impayée. Règlement sous 8 jours, sinon recouvrement contentieux.</p><p>{{signataire}}</p>",
     "variables":[{"key":"nom_debiteur","label":"Débiteur","type":"text","required":true},{"key":"adresse_debiteur","label":"Adresse","type":"textarea","required":true},{"key":"date","label":"Date","type":"date","required":true},{"key":"numero_facture","label":"N° facture","type":"text","required":true},{"key":"date_facture","label":"Date facture","type":"date","required":true},{"key":"montant","label":"Montant TTC","type":"number","required":true},{"key":"signataire","label":"Signataire","type":"text","required":true}],
     "legal_basis":[{"label":"C. com. L441-10"},{"label":"C. civ. art. 1231-6"}]},
    {"slug":"pv-ag-ordinaire","name":"PV d Assemblée Générale Ordinaire","description":"PV AGO approbation comptes","category":"societes","risk_level":"high","icon":"Landmark",
     "body":"<h1>PV AGO</h1><p>{{raison_sociale}}, {{forme_juridique}}, capital {{capital}} euros, siège {{siege}}, RCS {{rcs}}.</p><p>Le {{date_ag}} à {{heure_ag}}, AGO. Convocation : {{date_convocation}}.</p><p>Présents : {{associes_presents}}</p><h2>Résolution 1</h2><p>Approbation comptes clos le {{date_cloture}} : {{type_resultat}} de {{montant_resultat}} euros. Vote : {{vote_resolution_1}}.</p><h2>Résolution 2</h2><p>Affectation : {{affectation_resultat}}. Vote : {{vote_resolution_2}}.</p><p>Séance levée à {{heure_fin}}. {{president}}</p>",
     "variables":[{"key":"raison_sociale","label":"Raison sociale","type":"text","required":true},{"key":"forme_juridique","label":"Forme","type":"select","options":["SAS","SARL","SA","SASU","EURL"],"required":true},{"key":"capital","label":"Capital","type":"number","required":true},{"key":"siege","label":"Siège","type":"text","required":true},{"key":"rcs","label":"RCS","type":"text","required":true},{"key":"date_ag","label":"Date AG","type":"date","required":true},{"key":"heure_ag","label":"Heure","type":"text","required":true},{"key":"date_convocation","label":"Convocation","type":"date","required":true},{"key":"associes_presents","label":"Présents","type":"textarea","required":true},{"key":"date_cloture","label":"Clôture","type":"date","required":true},{"key":"type_resultat","label":"Type","type":"select","options":["bénéfice","perte"],"required":true},{"key":"montant_resultat","label":"Montant","type":"number","required":true},{"key":"vote_resolution_1","label":"Vote 1","type":"text","required":true},{"key":"affectation_resultat","label":"Affectation","type":"textarea","required":true},{"key":"vote_resolution_2","label":"Vote 2","type":"text","required":true},{"key":"heure_fin","label":"Heure fin","type":"text","required":true},{"key":"president","label":"Président","type":"text","required":true}],
     "legal_basis":[{"label":"C. com. L223-26"},{"label":"C. com. L227-9"}]},
    {"slug":"demande-rescrit-fiscal","name":"Demande de rescrit fiscal","description":"Rescrit DGFiP L80 B LPF","category":"fiscal","risk_level":"high","icon":"Calculator",
     "body":"<p>DGFiP - {{adresse_dgfip}}</p><p>{{lieu}}, le {{date}}</p><p>Objet : Rescrit fiscal - {{objet_rescrit}}</p><p>Conformément à L80 B LPF.</p><p>Identification : {{identification_contribuable}}</p><p>Faits : {{description_faits}}</p><p>Question : {{question}}</p><p>Analyse : {{analyse}}</p><p>{{signataire}}</p>",
     "variables":[{"key":"adresse_dgfip","label":"Adresse DGFiP","type":"text","required":true},{"key":"lieu","label":"Lieu","type":"text","required":true},{"key":"date","label":"Date","type":"date","required":true},{"key":"objet_rescrit","label":"Objet","type":"text","required":true},{"key":"identification_contribuable","label":"Identification","type":"textarea","required":true},{"key":"description_faits","label":"Faits","type":"textarea","required":true},{"key":"question","label":"Question","type":"textarea","required":true},{"key":"analyse","label":"Analyse","type":"textarea","required":true},{"key":"signataire","label":"Signataire","type":"text","required":true}],
     "legal_basis":[{"label":"LPF art. L80 B"}]},
    {"slug":"assignation-tj","name":"Assignation devant le Tribunal Judiciaire","description":"Trame assignation civile","category":"contentieux","risk_level":"critical","icon":"Gavel",
     "body":"<h1>Assignation TJ {{tribunal}}</h1><p>L AN {{annee}} ET LE {{date_assignation}}</p><p>À LA REQUÊTE DE : {{demandeur_identite}} - {{demandeur_adresse}}. Avocat : {{avocat_demandeur}}</p><p>J AI DONNÉ ASSIGNATION À : {{defendeur_identite}} - {{defendeur_adresse}}</p><p>Comparaître TJ {{tribunal}}, audience du {{date_audience}}.</p><h2>FAITS</h2><p>{{faits}}</p><h2>DISCUSSION</h2><p>{{discussion_juridique}}</p><h2>PAR CES MOTIFS</h2><p>{{demandes}}</p>",
     "variables":[{"key":"tribunal","label":"Tribunal","type":"text","required":true},{"key":"annee","label":"Année","type":"number","required":true},{"key":"date_assignation","label":"Date","type":"date","required":true},{"key":"demandeur_identite","label":"Demandeur","type":"textarea","required":true},{"key":"demandeur_adresse","label":"Adresse demandeur","type":"textarea","required":true},{"key":"avocat_demandeur","label":"Avocat","type":"text"},{"key":"defendeur_identite","label":"Défendeur","type":"textarea","required":true},{"key":"defendeur_adresse","label":"Adresse défendeur","type":"textarea","required":true},{"key":"date_audience","label":"Audience","type":"date","required":true},{"key":"faits","label":"Faits","type":"textarea","required":true},{"key":"discussion_juridique","label":"Discussion","type":"textarea","required":true},{"key":"demandes","label":"Demandes","type":"textarea","required":true}],
     "legal_basis":[{"label":"CPC art. 54"},{"label":"CPC art. 750-1"}]}
  ]'::jsonb;
  t jsonb;
BEGIN
  FOR t IN SELECT * FROM jsonb_array_elements(templates) LOOP
    IF NOT EXISTS (SELECT 1 FROM public.document_templates WHERE slug = t->>'slug' AND is_public = true) THEN
      INSERT INTO public.document_templates
        (slug, name, description, category, risk_level, icon, status, is_public, body, variables, legal_basis, tenant_id, created_by)
      VALUES
        (t->>'slug', t->>'name', t->>'description', t->>'category', t->>'risk_level', t->>'icon',
         'validated'::template_status, true, t->>'body', t->'variables', t->'legal_basis', NULL, NULL);
    END IF;
  END LOOP;
END $$;