INSERT INTO public.sensitive_actions_catalog (action_key,action_label,domain,severity,requires_human_validation,requires_lawyer,keywords,legal_refs,description) VALUES
('rh_embauche_cdi','Embauche CDI','rh','low',false,false,ARRAY['embauche cdi','contrat indeterminee','signature cdi']::text[],'[]'::jsonb,''),
('rh_embauche_cdd','Embauche CDD','rh','medium',true,false,ARRAY['embauche cdd','contrat determinee','cdd']::text[],'[]'::jsonb,''),
('rh_periode_essai_rupture','Rupture période d''essai','rh','high',true,false,ARRAY['rupture periode essai','fin essai','rompre essai']::text[],'[]'::jsonb,''),
('rh_renouvellement_cdd','Renouvellement CDD','rh','medium',true,false,ARRAY['renouvellement cdd','prolonger cdd']::text[],'[]'::jsonb,''),
('rh_requalification_cdd','Requalification CDD en CDI','rh','high',true,true,ARRAY['requalification cdd','requalifier cdd']::text[],'[]'::jsonb,''),
('rh_licenciement_inaptitude','Licenciement pour inaptitude','rh','critical',true,true,ARRAY['licenciement inaptitude']::text[],'[]'::jsonb,''),
('rh_licenciement_motif_personnel','Licenciement motif personnel non disciplinaire','rh','critical',true,true,ARRAY['licenciement motif personnel']::text[],'[]'::jsonb,''),
('rh_mise_a_pied_conservatoire','Mise à pied conservatoire','rh','high',true,false,ARRAY['mise a pied conservatoire']::text[],'[]'::jsonb,''),
('rh_mise_a_pied_disciplinaire','Mise à pied disciplinaire','rh','high',true,false,ARRAY['mise a pied disciplinaire']::text[],'[]'::jsonb,''),
('rh_avertissement','Avertissement disciplinaire','rh','medium',true,false,ARRAY['avertissement','blame','blâme']::text[],'[]'::jsonb,''),
('rh_mutation_disciplinaire','Mutation disciplinaire','rh','high',true,false,ARRAY['mutation disciplinaire']::text[],'[]'::jsonb,''),
('rh_retrogradation','Rétrogradation','rh','high',true,false,ARRAY['retrogradation','rétrogradation']::text[],'[]'::jsonb,''),
('rh_modification_contrat','Modification du contrat de travail','rh','high',true,false,ARRAY['modification contrat travail','avenant contrat travail']::text[],'[]'::jsonb,''),
('rh_changement_lieu_travail','Changement du lieu de travail','rh','medium',true,false,ARRAY['changement lieu travail','mutation geographique']::text[],'[]'::jsonb,''),
('rh_changement_horaires','Changement d''horaires importants','rh','medium',true,false,ARRAY['changement horaires','modification horaires']::text[],'[]'::jsonb,''),
('rh_passage_temps_partiel','Passage à temps partiel','rh','medium',true,false,ARRAY['passage temps partiel','temps partiel']::text[],'[]'::jsonb,''),
('rh_heures_supp','Recours aux heures supplémentaires','rh','low',false,false,ARRAY['heures supplementaires','heures sup']::text[],'[]'::jsonb,''),
('rh_forfait_jours','Mise en place forfait jours','rh','high',true,false,ARRAY['forfait jours']::text[],'[]'::jsonb,''),
('rh_teletravail_charte','Mise en place télétravail','rh','low',false,false,ARRAY['teletravail','télétravail','charte teletravail']::text[],'[]'::jsonb,''),
('rh_arret_maladie','Gestion arrêt maladie','rh','low',false,false,ARRAY['arret maladie','arrêt maladie']::text[],'[]'::jsonb,''),
('rh_atmp_declaration','Déclaration AT/MP','rh','high',true,false,ARRAY['accident travail','at mp','maladie professionnelle']::text[],'[]'::jsonb,''),
('rh_visite_medicale','Visite médicale obligatoire','rh','low',false,false,ARRAY['visite medicale','médecine du travail']::text[],'[]'::jsonb,''),
('rh_dpae','Déclaration préalable à l''embauche','rh','low',false,false,ARRAY['dpae','declaration prealable embauche']::text[],'[]'::jsonb,''),
('rh_solde_tout_compte','Solde de tout compte','rh','high',true,false,ARRAY['solde tout compte','stc']::text[],'[]'::jsonb,''),
('rh_certificat_travail','Certificat de travail','rh','low',false,false,ARRAY['certificat travail']::text[],'[]'::jsonb,''),
('rh_attestation_pole_emploi','Attestation Pôle Emploi / France Travail','rh','low',false,false,ARRAY['attestation pole emploi','france travail']::text[],'[]'::jsonb,''),
('rh_preavis_licenciement','Préavis de licenciement','rh','high',true,false,ARRAY['preavis licenciement','préavis']::text[],'[]'::jsonb,''),
('rh_dispense_preavis','Dispense de préavis','rh','medium',true,false,ARRAY['dispense preavis']::text[],'[]'::jsonb,''),
('rh_indemnite_licenciement','Calcul indemnité de licenciement','rh','high',true,false,ARRAY['indemnite licenciement','indemnité licenciement']::text[],'[]'::jsonb,''),
('rh_transaction_rupture','Transaction post-rupture','rh','critical',true,true,ARRAY['transaction rupture','protocole transactionnel']::text[],'[]'::jsonb,''),
('rh_clause_non_concurrence','Activation clause non-concurrence','rh','high',true,true,ARRAY['clause non concurrence','non concurrence']::text[],'[]'::jsonb,''),
('rh_renonciation_non_concurrence','Renonciation à clause non-concurrence','rh','high',true,false,ARRAY['renonciation non concurrence']::text[],'[]'::jsonb,''),
('rh_proces_verbal_cse','PV CSE','rh','low',false,false,ARRAY['proces verbal cse','pv cse']::text[],'[]'::jsonb,''),
('rh_consultation_cse','Consultation CSE','rh','medium',true,false,ARRAY['consultation cse','consulter cse']::text[],'[]'::jsonb,''),
('rh_election_cse','Élection CSE','rh','high',true,false,ARRAY['election cse','élections cse']::text[],'[]'::jsonb,''),
('rh_droit_alerte_cse','Droit d''alerte CSE','rh','high',true,false,ARRAY['droit alerte cse']::text[],'[]'::jsonb,''),
('rh_negociation_accord','Négociation accord collectif','rh','high',true,false,ARRAY['accord collectif','negociation collective','nao']::text[],'[]'::jsonb,''),
('rh_denonciation_accord','Dénonciation accord collectif','rh','high',true,true,ARRAY['denonciation accord','dénoncer accord collectif']::text[],'[]'::jsonb,''),
('rh_reglement_interieur','Modification règlement intérieur','rh','medium',true,false,ARRAY['reglement interieur','règlement intérieur']::text[],'[]'::jsonb,''),
('rh_grille_salaires','Modification grille salariale','rh','medium',true,false,ARRAY['grille salariale','modification salaire']::text[],'[]'::jsonb,''),
('rh_alerte_harcelement','Signalement harcèlement','rh','critical',true,true,ARRAY['harcelement moral','harcèlement','harcelement sexuel']::text[],'[]'::jsonb,''),
('rh_enquete_interne','Enquête interne disciplinaire','rh','high',true,false,ARRAY['enquete interne','enquête interne']::text[],'[]'::jsonb,''),
('rh_droit_retrait','Droit de retrait','rh','high',true,false,ARRAY['droit de retrait']::text[],'[]'::jsonb,''),
('rh_greve_gestion','Gestion d''une grève','rh','high',true,true,ARRAY['greve','grève','piquet']::text[],'[]'::jsonb,''),
('rh_lock_out','Lock-out','rh','critical',true,true,ARRAY['lock out','lock-out']::text[],'[]'::jsonb,''),
('rh_apprentissage_contrat','Contrat d''apprentissage','rh','medium',true,false,ARRAY['contrat apprentissage','apprenti']::text[],'[]'::jsonb,''),
('rh_professionnalisation','Contrat de professionnalisation','rh','medium',true,false,ARRAY['contrat professionnalisation']::text[],'[]'::jsonb,''),
('rh_stage_convention','Convention de stage','rh','low',false,false,ARRAY['convention stage','stagiaire']::text[],'[]'::jsonb,''),
('rh_alternance','Convention d''alternance','rh','medium',true,false,ARRAY['alternance']::text[],'[]'::jsonb,''),
('rh_egalite_index','Index égalité H/F','rh','medium',true,false,ARRAY['index egalite','egalite professionnelle']::text[],'[]'::jsonb,''),
('rh_bdes_mise_a_jour','BDES / BDESE mise à jour','rh','medium',true,false,ARRAY['bdese','bdes','base donnees economiques']::text[],'[]'::jsonb,''),
('rh_doc_unique_dur','Document unique DUERP','rh','high',true,false,ARRAY['duerp','document unique','document unique evaluation']::text[],'[]'::jsonb,''),
('rh_plan_action_rps','Plan d''action RPS','rh','medium',true,false,ARRAY['plan action rps','risques psychosociaux']::text[],'[]'::jsonb,''),
('rh_remuneration_variable','Mise en place rémunération variable','rh','medium',true,false,ARRAY['remuneration variable','prime objectifs']::text[],'[]'::jsonb,''),
('rh_interessement','Accord d''intéressement','rh','high',true,false,ARRAY['accord interessement','intéressement']::text[],'[]'::jsonb,''),
('rh_participation','Accord de participation','rh','high',true,false,ARRAY['accord participation','participation salariés']::text[],'[]'::jsonb,''),
('com_signature_cgv','Mise à jour CGV','commercial','medium',true,false,ARRAY['cgv','conditions generales vente']::text[],'[]'::jsonb,''),
('com_signature_cgu','Mise à jour CGU','commercial','medium',true,false,ARRAY['cgu','conditions generales utilisation']::text[],'[]'::jsonb,''),
('com_clause_penale','Activation clause pénale','commercial','high',true,true,ARRAY['clause penale','clause pénale']::text[],'[]'::jsonb,''),
('com_negociation_remise','Négociation remise commerciale','commercial','low',false,false,ARRAY['remise commerciale','negociation prix']::text[],'[]'::jsonb,''),
('com_partenariat_signature','Signature contrat de partenariat','commercial','medium',true,false,ARRAY['contrat partenariat']::text[],'[]'::jsonb,''),
('com_distribution_exclusive','Contrat de distribution exclusive','commercial','high',true,true,ARRAY['distribution exclusive']::text[],'[]'::jsonb,''),
('com_franchise_signature','Contrat de franchise','commercial','high',true,true,ARRAY['contrat franchise']::text[],'[]'::jsonb,''),
('com_agent_commercial','Contrat d''agent commercial','commercial','high',true,true,ARRAY['agent commercial']::text[],'[]'::jsonb,''),
('com_rupture_brutale_relation','Rupture brutale relation commerciale','commercial','critical',true,true,ARRAY['rupture brutale','rupture relation commerciale']::text[],'[]'::jsonb,''),
('com_pratiques_restrictives','Pratiques restrictives concurrence','commercial','critical',true,true,ARRAY['pratique restrictive','desequilibre significatif']::text[],'[]'::jsonb,''),
('com_concurrence_deloyale','Action concurrence déloyale','commercial','critical',true,true,ARRAY['concurrence deloyale','concurrence déloyale']::text[],'[]'::jsonb,''),
('com_parasitisme','Action parasitisme','commercial','high',true,true,ARRAY['parasitisme commercial']::text[],'[]'::jsonb,''),
('com_denigrement','Action dénigrement','commercial','high',true,true,ARRAY['denigrement','dénigrement']::text[],'[]'::jsonb,''),
('com_clause_exclusivite','Clause d''exclusivité','commercial','high',true,true,ARRAY['clause exclusivite','clause d''exclusivité']::text[],'[]'::jsonb,''),
('com_clause_compromissoire','Clause d''arbitrage','commercial','high',true,true,ARRAY['clause compromissoire','clause arbitrage']::text[],'[]'::jsonb,''),
('com_clause_attributive','Clause attributive de juridiction','commercial','medium',true,false,ARRAY['clause attributive juridiction']::text[],'[]'::jsonb,''),
('com_garantie_passif','Garantie d''actif et passif','commercial','critical',true,true,ARRAY['garantie actif passif','gap']::text[],'[]'::jsonb,''),
('com_lettre_intention','Lettre d''intention','commercial','medium',true,false,ARRAY['lettre intention','loi']::text[],'[]'::jsonb,''),
('com_pacte_actionnaires','Pacte d''actionnaires','commercial','critical',true,true,ARRAY['pacte actionnaires','pacte associes']::text[],'[]'::jsonb,''),
('com_due_diligence','Due diligence','commercial','high',true,true,ARRAY['due diligence']::text[],'[]'::jsonb,''),
('com_signature_nda','Signature NDA / accord de confidentialité','commercial','medium',true,false,ARRAY['nda','accord confidentialite','non disclosure']::text[],'[]'::jsonb,''),
('com_protocole_accord','Protocole d''accord','commercial','high',true,true,ARRAY['protocole accord','protocole transaction']::text[],'[]'::jsonb,''),
('com_levee_clause_resolutoire','Mise en œuvre clause résolutoire','commercial','critical',true,true,ARRAY['clause resolutoire','clause résolutoire']::text[],'[]'::jsonb,''),
('com_assignation_referee','Assignation en référé','commercial','critical',true,true,ARRAY['assignation refere','référé']::text[],'[]'::jsonb,''),
('com_saisie_conservatoire','Saisie conservatoire','commercial','critical',true,true,ARRAY['saisie conservatoire']::text[],'[]'::jsonb,''),
('com_saisie_attribution','Saisie-attribution','commercial','critical',true,true,ARRAY['saisie attribution']::text[],'[]'::jsonb,''),
('com_injonction_payer','Injonction de payer','commercial','high',true,false,ARRAY['injonction payer','injonction de payer']::text[],'[]'::jsonb,''),
('com_redressement_judiciaire','Déclaration de cessation de paiements','commercial','critical',true,true,ARRAY['cessation paiements','redressement judiciaire','liquidation judiciaire']::text[],'[]'::jsonb,''),
('com_sauvegarde','Procédure de sauvegarde','commercial','critical',true,true,ARRAY['procedure sauvegarde']::text[],'[]'::jsonb,''),
('com_conciliation','Procédure de conciliation','commercial','high',true,true,ARRAY['procedure conciliation']::text[],'[]'::jsonb,''),
('com_mediation_commerciale','Médiation commerciale','commercial','medium',true,false,ARRAY['mediation commerciale','médiation']::text[],'[]'::jsonb,''),
('com_resiliation_unilaterale','Résiliation unilatérale contrat','commercial','high',true,true,ARRAY['resiliation unilaterale','résiliation unilatérale']::text[],'[]'::jsonb,''),
('com_avenant_prix','Avenant tarifaire majeur','commercial','high',true,false,ARRAY['avenant tarifaire','revision prix']::text[],'[]'::jsonb,''),
('com_recouvrement_amiable','Recouvrement amiable','commercial','low',false,false,ARRAY['recouvrement amiable','relance impayes']::text[],'[]'::jsonb,''),
('soc_creation_sas','Création SAS','societes','medium',true,false,ARRAY['creation sas','constitution sas']::text[],'[]'::jsonb,''),
('soc_creation_sarl','Création SARL','societes','medium',true,false,ARRAY['creation sarl','constitution sarl']::text[],'[]'::jsonb,''),
('soc_creation_sci','Création SCI','societes','medium',true,false,ARRAY['creation sci','constitution sci']::text[],'[]'::jsonb,''),
('soc_creation_eurl','Création EURL','societes','medium',true,false,ARRAY['creation eurl','constitution eurl']::text[],'[]'::jsonb,''),
('soc_modification_statuts','Modification des statuts','societes','high',true,true,ARRAY['modification statuts','statuts modification']::text[],'[]'::jsonb,''),
('soc_changement_dirigeant','Changement de dirigeant','societes','high',true,false,ARRAY['changement dirigeant','nomination dirigeant']::text[],'[]'::jsonb,''),
('soc_revocation_dirigeant','Révocation de dirigeant','societes','critical',true,true,ARRAY['revocation dirigeant','révocation dirigeant']::text[],'[]'::jsonb,''),
('soc_demission_dirigeant','Démission de dirigeant','societes','high',true,false,ARRAY['demission dirigeant','démission dirigeant']::text[],'[]'::jsonb,''),
('soc_assemblee_generale','Assemblée générale ordinaire','societes','medium',true,false,ARRAY['assemblee generale','ago','ag ordinaire']::text[],'[]'::jsonb,''),
('soc_assemblee_extra','Assemblée générale extraordinaire','societes','high',true,false,ARRAY['assemblee extraordinaire','age','ag extraordinaire']::text[],'[]'::jsonb,''),
('soc_approbation_comptes','Approbation des comptes annuels','societes','medium',true,false,ARRAY['approbation comptes']::text[],'[]'::jsonb,''),
('soc_distribution_dividendes','Distribution de dividendes','societes','high',true,false,ARRAY['distribution dividendes','dividendes']::text[],'[]'::jsonb,''),
('soc_augmentation_capital','Augmentation de capital','societes','high',true,true,ARRAY['augmentation capital']::text[],'[]'::jsonb,''),
('soc_reduction_capital','Réduction de capital','societes','critical',true,true,ARRAY['reduction capital','réduction capital']::text[],'[]'::jsonb,''),
('soc_fusion','Fusion-absorption','societes','critical',true,true,ARRAY['fusion absorption','traite fusion']::text[],'[]'::jsonb,''),
('soc_scission','Scission de société','societes','critical',true,true,ARRAY['scission societe']::text[],'[]'::jsonb,''),
('soc_apport_partiel','Apport partiel d''actif','societes','critical',true,true,ARRAY['apport partiel actif']::text[],'[]'::jsonb,''),
('soc_transfert_siege','Transfert de siège social','societes','medium',true,false,ARRAY['transfert siege','transfert siège']::text[],'[]'::jsonb,''),
('soc_changement_objet','Changement d''objet social','societes','high',true,true,ARRAY['changement objet social']::text[],'[]'::jsonb,''),
('soc_changement_denomination','Changement de dénomination','societes','medium',true,false,ARRAY['changement denomination']::text[],'[]'::jsonb,''),
('soc_transformation_forme','Transformation forme juridique','societes','high',true,true,ARRAY['transformation societe','sas en sarl']::text[],'[]'::jsonb,''),
('soc_liquidation_amiable','Liquidation amiable','societes','critical',true,true,ARRAY['liquidation amiable']::text[],'[]'::jsonb,''),
('soc_radiation_rcs','Radiation RCS','societes','high',true,false,ARRAY['radiation rcs']::text[],'[]'::jsonb,''),
('soc_immatriculation_rcs','Immatriculation RCS','societes','medium',true,false,ARRAY['immatriculation rcs']::text[],'[]'::jsonb,''),
('soc_depot_compte_annuel','Dépôt comptes annuels','societes','medium',true,false,ARRAY['depot comptes annuels']::text[],'[]'::jsonb,''),
('soc_nomination_cac','Nomination commissaire aux comptes','societes','high',true,true,ARRAY['commissaire aux comptes','cac']::text[],'[]'::jsonb,''),
('soc_convention_reglementee','Convention réglementée','societes','high',true,true,ARRAY['convention reglementee','convention réglementée']::text[],'[]'::jsonb,''),
('soc_apport_nature','Apport en nature','societes','high',true,true,ARRAY['apport en nature','commissaire apports']::text[],'[]'::jsonb,''),
('soc_quasi_apport','Quasi-apport','societes','high',true,true,ARRAY['quasi apport']::text[],'[]'::jsonb,''),
('soc_caution_dirigeant','Caution personnelle du dirigeant','societes','critical',true,true,ARRAY['caution dirigeant','cautionnement']::text[],'[]'::jsonb,''),
('rgpd_registre_traitements','Tenue registre des traitements','rgpd','medium',true,false,ARRAY['registre traitements','registre traitement']::text[],'[]'::jsonb,''),
('rgpd_designation_dpo','Désignation DPO','rgpd','high',true,false,ARRAY['designation dpo','délégué protection donnees']::text[],'[]'::jsonb,''),
('rgpd_information_personnes','Information des personnes concernées','rgpd','medium',true,false,ARRAY['information personnes','mention rgpd']::text[],'[]'::jsonb,''),
('rgpd_consentement_collecte','Recueil consentement','rgpd','medium',true,false,ARRAY['recueil consentement','collecte consentement']::text[],'[]'::jsonb,''),
('rgpd_droit_acces','Réponse droit d''accès','rgpd','high',true,false,ARRAY['droit acces','droit d''acces rgpd']::text[],'[]'::jsonb,''),
('rgpd_droit_effacement','Réponse droit à l''effacement','rgpd','high',true,false,ARRAY['droit effacement','droit oubli']::text[],'[]'::jsonb,''),
('rgpd_droit_portabilite','Réponse droit à la portabilité','rgpd','high',true,false,ARRAY['droit portabilite']::text[],'[]'::jsonb,''),
('rgpd_droit_rectification','Réponse droit de rectification','rgpd','medium',true,false,ARRAY['droit rectification']::text[],'[]'::jsonb,''),
('rgpd_droit_opposition','Réponse droit d''opposition','rgpd','high',true,false,ARRAY['droit opposition']::text[],'[]'::jsonb,''),
('rgpd_transfert_hors_ue','Transfert de données hors UE','rgpd','critical',true,true,ARRAY['transfert hors ue','transfert international']::text[],'[]'::jsonb,''),
('rgpd_clauses_contractuelles','Mise en place clauses contractuelles types','rgpd','high',true,true,ARRAY['clauses contractuelles types','ccs']::text[],'[]'::jsonb,''),
('rgpd_sous_traitant_signature','Contrat de sous-traitance RGPD article 28','rgpd','high',true,false,ARRAY['sous-traitant rgpd','article 28']::text[],'[]'::jsonb,''),
('rgpd_audit_conformite','Audit de conformité RGPD','rgpd','medium',true,false,ARRAY['audit conformite rgpd']::text[],'[]'::jsonb,''),
('rgpd_cookies_banner','Mise en place bandeau cookies','rgpd','medium',true,false,ARRAY['bandeau cookies','gestion cookies']::text[],'[]'::jsonb,''),
('rgpd_charte_informatique','Charte informatique','rgpd','medium',true,false,ARRAY['charte informatique']::text[],'[]'::jsonb,''),
('rgpd_plan_continuite','Plan de continuité données','rgpd','high',true,false,ARRAY['plan continuite donnees']::text[],'[]'::jsonb,''),
('rgpd_formation_personnel','Formation RGPD du personnel','rgpd','low',false,false,ARRAY['formation rgpd','sensibilisation rgpd']::text[],'[]'::jsonb,''),
('rgpd_notification_cnil','Notification CNIL violation','rgpd','critical',true,true,ARRAY['notification cnil','violation donnees cnil']::text[],'[]'::jsonb,''),
('fis_declaration_tva','Déclaration TVA','fiscal','low',false,false,ARRAY['declaration tva','ca3','ca12']::text[],'[]'::jsonb,''),
('fis_declaration_is','Déclaration IS','fiscal','medium',true,false,ARRAY['declaration is','liasse fiscale']::text[],'[]'::jsonb,''),
('fis_liasse_fiscale','Dépôt liasse fiscale','fiscal','medium',true,false,ARRAY['liasse fiscale','2065']::text[],'[]'::jsonb,''),
('fis_cvae','Déclaration CVAE','fiscal','medium',true,false,ARRAY['cvae','cotisation valeur ajoutee']::text[],'[]'::jsonb,''),
('fis_cfe','Déclaration CFE','fiscal','low',false,false,ARRAY['cfe','cotisation fonciere']::text[],'[]'::jsonb,''),
('fis_cice_cir','Déclaration CICE / CIR','fiscal','high',true,true,ARRAY['credit impot recherche','cir','cice']::text[],'[]'::jsonb,''),
('fis_controle_fiscal','Contrôle fiscal','fiscal','critical',true,true,ARRAY['controle fiscal','contrôle fiscal','verification comptabilite']::text[],'[]'::jsonb,''),
('fis_avis_imposition','Réponse avis d''imposition','fiscal','medium',true,false,ARRAY['avis imposition']::text[],'[]'::jsonb,''),
('fis_proposition_rectification','Réponse proposition rectification','fiscal','critical',true,true,ARRAY['proposition rectification','2120']::text[],'[]'::jsonb,''),
('fis_recours_contentieux','Recours contentieux fiscal','fiscal','critical',true,true,ARRAY['recours contentieux fiscal']::text[],'[]'::jsonb,''),
('fis_demande_remise','Demande de remise gracieuse','fiscal','medium',true,false,ARRAY['remise gracieuse','demande remise']::text[],'[]'::jsonb,''),
('fis_delai_paiement','Demande délai de paiement','fiscal','low',false,false,ARRAY['delai paiement impots','echeancier impots']::text[],'[]'::jsonb,''),
('fis_rescrit_fiscal','Rescrit fiscal','fiscal','high',true,true,ARRAY['rescrit fiscal']::text[],'[]'::jsonb,''),
('fis_option_is','Option pour l''IS','fiscal','high',true,true,ARRAY['option is','option impot societes']::text[],'[]'::jsonb,''),
('fis_renoncia_franchise_tva','Renonciation franchise TVA','fiscal','medium',true,false,ARRAY['renonciation franchise tva']::text[],'[]'::jsonb,''),
('fis_regime_micro','Choix régime micro','fiscal','low',false,false,ARRAY['regime micro','micro entrepreneur']::text[],'[]'::jsonb,''),
('fis_dsn','Déclaration DSN','fiscal','low',false,false,ARRAY['dsn','declaration sociale nominative']::text[],'[]'::jsonb,''),
('fis_urssaf_controle','Contrôle URSSAF','fiscal','critical',true,true,ARRAY['controle urssaf','contrôle urssaf']::text[],'[]'::jsonb,''),
('fis_taxe_apprentissage','Taxe d''apprentissage','fiscal','low',false,false,ARRAY['taxe apprentissage']::text[],'[]'::jsonb,''),
('fis_pas_employeur','Prélèvement à la source employeur','fiscal','medium',true,false,ARRAY['prelevement a la source','pas employeur']::text[],'[]'::jsonb,''),
('fis_intracom_tva','TVA intracommunautaire','fiscal','medium',true,false,ARRAY['tva intracommunautaire','numero tva intra']::text[],'[]'::jsonb,''),
('fis_dac6','Déclaration DAC6','fiscal','high',true,true,ARRAY['dac6','dispositif transfrontiere']::text[],'[]'::jsonb,''),
('cnt_referee_heure','Référé d''heure à heure','contentieux','critical',true,true,ARRAY['refere heure heure']::text[],'[]'::jsonb,''),
('cnt_requete_unilaterale','Requête unilatérale','contentieux','high',true,true,ARRAY['requete unilaterale','ordonnance sur requete']::text[],'[]'::jsonb,''),
('cnt_signification_jugement','Signification de jugement','contentieux','high',true,false,ARRAY['signification jugement']::text[],'[]'::jsonb,''),
('cnt_execution_provisoire','Demande exécution provisoire','contentieux','high',true,true,ARRAY['execution provisoire']::text[],'[]'::jsonb,''),
('cnt_radiation_role','Radiation du rôle','contentieux','medium',true,false,ARRAY['radiation role']::text[],'[]'::jsonb,''),
('cnt_desistement','Désistement d''instance','contentieux','high',true,true,ARRAY['desistement instance','désistement']::text[],'[]'::jsonb,''),
('cnt_pourvoi_cassation','Pourvoi en cassation','contentieux','critical',true,true,ARRAY['pourvoi cassation','cassation']::text[],'[]'::jsonb,''),
('cnt_pourvoi_conseil_etat','Pourvoi Conseil d''État','contentieux','critical',true,true,ARRAY['pourvoi conseil etat','conseil d''etat']::text[],'[]'::jsonb,''),
('cnt_recours_grace','Recours en grâce','contentieux','high',true,true,ARRAY['recours grace']::text[],'[]'::jsonb,''),
('cnt_constitution_partie_civile','Constitution de partie civile','contentieux','critical',true,true,ARRAY['constitution partie civile','partie civile']::text[],'[]'::jsonb,''),
('cnt_plainte_simple','Plainte simple','contentieux','high',true,true,ARRAY['plainte simple','depot plainte']::text[],'[]'::jsonb,''),
('cnt_plainte_avec_pc','Plainte avec constitution PC','contentieux','critical',true,true,ARRAY['plainte constitution partie civile']::text[],'[]'::jsonb,''),
('cnt_citation_directe','Citation directe','contentieux','critical',true,true,ARRAY['citation directe']::text[],'[]'::jsonb,''),
('cnt_qpc','Question prioritaire de constitutionnalité','contentieux','critical',true,true,ARRAY['question prioritaire constitutionnalite','qpc']::text[],'[]'::jsonb,''),
('cnt_recours_eur','Recours CEDH','contentieux','critical',true,true,ARRAY['recours cedh','cour europeenne droits homme']::text[],'[]'::jsonb,''),
('cnt_huissier_constat','Constat d''huissier / commissaire de justice','contentieux','medium',true,false,ARRAY['constat huissier','commissaire justice']::text[],'[]'::jsonb,''),
('cnt_expertise_judiciaire','Demande d''expertise judiciaire','contentieux','high',true,true,ARRAY['expertise judiciaire']::text[],'[]'::jsonb,''),
('cnt_provision','Demande de provision','contentieux','high',true,true,ARRAY['demande provision']::text[],'[]'::jsonb,''),
('cnt_astreinte','Demande d''astreinte','contentieux','high',true,true,ARRAY['demande astreinte','astreinte']::text[],'[]'::jsonb,''),
('cnt_compromis','Compromis d''arbitrage','contentieux','high',true,true,ARRAY['compromis arbitrage']::text[],'[]'::jsonb,''),
('cnt_sentence_arbitrale','Exequatur sentence arbitrale','contentieux','critical',true,true,ARRAY['exequatur','sentence arbitrale']::text[],'[]'::jsonb,''),
('cnt_aj_demande','Demande aide juridictionnelle','contentieux','low',false,false,ARRAY['aide juridictionnelle']::text[],'[]'::jsonb,''),
('cnt_revisione','Recours en révision','contentieux','critical',true,true,ARRAY['recours revision']::text[],'[]'::jsonb,''),
('cnt_tierce_opposition','Tierce opposition','contentieux','high',true,true,ARRAY['tierce opposition']::text[],'[]'::jsonb,''),
('cnt_opposition_jugement','Opposition à jugement','contentieux','high',true,true,ARRAY['opposition jugement']::text[],'[]'::jsonb,''),
('ctr_signature_bail_commercial','Signature bail commercial','contrats','high',true,true,ARRAY['bail commercial','signature bail commercial']::text[],'[]'::jsonb,''),
('ctr_renouvellement_bail','Renouvellement bail commercial','contrats','high',true,true,ARRAY['renouvellement bail','triennal']::text[],'[]'::jsonb,''),
('ctr_resiliation_bail','Résiliation bail commercial','contrats','critical',true,true,ARRAY['resiliation bail commercial','conge bail']::text[],'[]'::jsonb,''),
('ctr_bail_habitation','Bail d''habitation','contrats','medium',true,false,ARRAY['bail habitation','bail loi 89']::text[],'[]'::jsonb,''),
('ctr_signature_prestation_services','Contrat de prestation de services','contrats','medium',true,false,ARRAY['contrat prestation services']::text[],'[]'::jsonb,''),
('ctr_signature_sous_traitance','Contrat de sous-traitance','contrats','high',true,false,ARRAY['contrat sous-traitance','sous-traitance']::text[],'[]'::jsonb,''),
('ctr_signature_licence','Contrat de licence','contrats','high',true,true,ARRAY['contrat licence','licence logiciel']::text[],'[]'::jsonb,''),
('ctr_signature_cession_droits','Cession de droits IP','contrats','high',true,true,ARRAY['cession droits','cession ip','cession propriete intellectuelle']::text[],'[]'::jsonb,''),
('ctr_signature_cession_marque','Cession de marque','contrats','high',true,true,ARRAY['cession marque']::text[],'[]'::jsonb,''),
('ctr_depot_marque','Dépôt de marque INPI','contrats','medium',true,false,ARRAY['depot marque','inpi marque']::text[],'[]'::jsonb,''),
('ctr_depot_brevet','Dépôt de brevet','contrats','high',true,true,ARRAY['depot brevet']::text[],'[]'::jsonb,''),
('ctr_depot_dessin_modele','Dépôt dessin et modèle','contrats','medium',true,false,ARRAY['dessin modele','depot dessin']::text[],'[]'::jsonb,''),
('ctr_signature_assurance','Souscription contrat d''assurance pro','contrats','medium',true,false,ARRAY['contrat assurance','souscription assurance']::text[],'[]'::jsonb,''),
('ctr_resiliation_assurance','Résiliation contrat d''assurance','contrats','medium',true,false,ARRAY['resiliation assurance']::text[],'[]'::jsonb,''),
('ctr_signature_pret','Souscription emprunt bancaire','contrats','high',true,false,ARRAY['pret bancaire','emprunt']::text[],'[]'::jsonb,''),
('ctr_garantie_caution','Mise en place caution bancaire','contrats','high',true,true,ARRAY['caution bancaire']::text[],'[]'::jsonb,''),
('ctr_signature_credit_bail','Signature crédit-bail','contrats','high',true,false,ARRAY['credit bail','leasing']::text[],'[]'::jsonb,''),
('ctr_avenant_mineur','Avenant mineur','contrats','low',false,false,ARRAY['avenant mineur']::text[],'[]'::jsonb,''),
('ctr_renegociation_contrat','Renégociation contrat','contrats','medium',true,false,ARRAY['renegociation contrat','imprevision']::text[],'[]'::jsonb,''),
('ctr_clause_revision_prix','Clause de révision de prix','contrats','medium',true,false,ARRAY['clause revision prix','indexation prix']::text[],'[]'::jsonb,''),
('ctr_force_majeure','Invocation force majeure','contrats','high',true,true,ARRAY['force majeure']::text[],'[]'::jsonb,''),
('ctr_imprevision','Invocation imprévision','contrats','high',true,true,ARRAY['imprevision','article 1195']::text[],'[]'::jsonb,''),
('adm_demande_autorisation','Demande d''autorisation administrative','administratif','medium',true,false,ARRAY['demande autorisation','autorisation administrative']::text[],'[]'::jsonb,''),
('adm_permis_construire','Demande permis de construire','administratif','high',true,false,ARRAY['permis construire']::text[],'[]'::jsonb,''),
('adm_declaration_prealable','Déclaration préalable de travaux','administratif','medium',true,false,ARRAY['declaration prealable travaux']::text[],'[]'::jsonb,''),
('adm_recours_gracieux','Recours gracieux','administratif','medium',true,false,ARRAY['recours gracieux']::text[],'[]'::jsonb,''),
('adm_recours_contentieux','Recours contentieux administratif','administratif','critical',true,true,ARRAY['recours contentieux administratif','ta']::text[],'[]'::jsonb,''),
('adm_refere_suspension','Référé-suspension','administratif','critical',true,true,ARRAY['refere suspension']::text[],'[]'::jsonb,''),
('adm_refere_liberte','Référé-liberté','administratif','critical',true,true,ARRAY['refere liberte']::text[],'[]'::jsonb,''),
('adm_demande_subvention','Demande de subvention publique','administratif','low',false,false,ARRAY['demande subvention']::text[],'[]'::jsonb,''),
('adm_marche_public_repondre','Réponse marché public','administratif','medium',true,false,ARRAY['marche public','appel offres','aap']::text[],'[]'::jsonb,''),
('adm_marche_public_recours','Recours marché public','administratif','critical',true,true,ARRAY['recours marche public','refere precontractuel']::text[],'[]'::jsonb,''),
('adm_dsn_employeur','DSN employeur','administratif','low',false,false,ARRAY['dsn']::text[],'[]'::jsonb,''),
('adm_kbis_demande','Demande de Kbis','administratif','low',false,false,ARRAY['kbis']::text[],'[]'::jsonb,''),
('adm_attestation_vigilance','Attestation de vigilance URSSAF','administratif','low',false,false,ARRAY['attestation vigilance']::text[],'[]'::jsonb,''),
('adm_certificat_urbanisme','Certificat d''urbanisme','administratif','medium',true,false,ARRAY['certificat urbanisme']::text[],'[]'::jsonb,''),
('adm_ich','ICPE déclaration','administratif','high',true,true,ARRAY['icpe','installation classee']::text[],'[]'::jsonb,'')
ON CONFLICT (action_key) DO NOTHING;