
INSERT INTO public.sensitive_actions_catalog
  (action_key, action_label, domain, severity, requires_human_validation, requires_lawyer, keywords, legal_refs, description)
VALUES
  -- RH
  ('rh_licenciement_faute',          'Licenciement pour faute',                    'rh',          'critical', true, true,
   ARRAY['licenciement','faute','sanction','disciplinaire'],
   '[{"code":"L1232-1","source":"Code du travail"},{"code":"L1331-1","source":"Code du travail"}]'::jsonb,
   'Procédure disciplinaire avec licenciement — risque prud''homal majeur.'),
  ('rh_licenciement_eco',            'Licenciement pour motif économique',         'rh',          'critical', true, true,
   ARRAY['licenciement économique','PSE','suppression poste'],
   '[{"code":"L1233-3","source":"Code du travail"}]'::jsonb,
   'Procédure de licenciement économique — formalisme strict.'),
  ('rh_rupture_conventionnelle',     'Rupture conventionnelle',                    'rh',          'high',     true, false,
   ARRAY['rupture conventionnelle','homologation','dreets'],
   '[{"code":"L1237-11","source":"Code du travail"}]'::jsonb,
   'Rupture amiable nécessitant homologation administrative.'),
  ('rh_sanction_disciplinaire',      'Sanction disciplinaire',                     'rh',          'high',     true, false,
   ARRAY['sanction','avertissement','mise à pied','blâme'],
   '[{"code":"L1331-1","source":"Code du travail"}]'::jsonb,
   'Sanction disciplinaire — entretien préalable requis au-delà de l''avertissement.'),
  ('rh_inaptitude',                  'Constat d''inaptitude / reclassement',       'rh',          'high',     true, true,
   ARRAY['inaptitude','reclassement','médecin du travail'],
   '[{"code":"L1226-2","source":"Code du travail"}]'::jsonb,
   'Procédure post-avis d''inaptitude — recherche reclassement obligatoire.'),
  ('rh_pse',                         'Plan de sauvegarde de l''emploi',            'rh',          'critical', true, true,
   ARRAY['PSE','plan social','grand licenciement'],
   '[{"code":"L1233-61","source":"Code du travail"}]'::jsonb,
   'PSE : ≥ 10 licenciements sur 30 jours, entreprise ≥ 50 salariés.'),

  -- Commercial
  ('com_mise_en_demeure',            'Mise en demeure commerciale',                'commercial',  'high',     true, false,
   ARRAY['mise en demeure','MED','injonction','impayé'],
   '[{"code":"1344","source":"Code civil"}]'::jsonb,
   'Acte préalable au contentieux — fait courir les intérêts de retard.'),
  ('com_transaction',                'Transaction commerciale',                    'commercial',  'critical', true, true,
   ARRAY['transaction','protocole','accord transactionnel'],
   '[{"code":"2044","source":"Code civil"},{"code":"2052","source":"Code civil"}]'::jsonb,
   'Transaction = renonciation définitive au procès — autorité de chose jugée.'),
  ('com_resiliation_contrat',        'Résiliation de contrat commercial',          'commercial',  'high',     true, false,
   ARRAY['résiliation','rupture','contrat'],
   '[{"code":"1224","source":"Code civil"},{"code":"L442-1","source":"Code de commerce"}]'::jsonb,
   'Rupture brutale = risque de dommages-intérêts (préavis insuffisant).'),
  ('com_recouvrement_judiciaire',    'Recouvrement judiciaire (injonction de payer)','commercial','high',   true, false,
   ARRAY['injonction de payer','recouvrement','impayé'],
   '[{"code":"1405","source":"Code de procédure civile"}]'::jsonb,
   'Procédure d''injonction — requête au tribunal compétent.'),

  -- Sociétés
  ('soc_cession_parts',              'Cession de parts sociales / actions',        'societes',    'critical', true, true,
   ARRAY['cession','parts','actions','agrément'],
   '[{"code":"L223-14","source":"Code de commerce"}]'::jsonb,
   'Cession parts — formalisme statutaire, agrément, enregistrement fiscal.'),
  ('soc_age_modification',           'Assemblée générale extraordinaire',          'societes',    'high',     true, false,
   ARRAY['AGE','assemblée extraordinaire','statuts','modification'],
   '[{"code":"L225-96","source":"Code de commerce"}]'::jsonb,
   'AGE — quorum et majorité renforcés, dépôt PV au greffe.'),
  ('soc_depot_legal',                'Dépôt légal au greffe',                      'societes',    'high',     true, false,
   ARRAY['dépôt légal','greffe','formalité','RCS'],
   '[{"code":"R123-66","source":"Code de commerce"}]'::jsonb,
   'Dépôt obligatoire des actes — délais légaux à respecter.'),
  ('soc_dissolution',                'Dissolution de société',                     'societes',    'critical', true, true,
   ARRAY['dissolution','liquidation','clôture'],
   '[{"code":"L237-1","source":"Code de commerce"}]'::jsonb,
   'Dissolution + liquidation — procédure longue, formalités multiples.'),

  -- RGPD
  ('rgpd_violation_donnees',         'Notification violation de données',          'rgpd',        'critical', true, false,
   ARRAY['violation','data breach','notification CNIL','72h'],
   '[{"code":"33","source":"RGPD"},{"code":"34","source":"RGPD"}]'::jsonb,
   'Notification CNIL sous 72h obligatoire si risque pour les personnes.'),
  ('rgpd_dpia',                      'Analyse d''impact (DPIA / AIPD)',            'rgpd',        'high',     true, false,
   ARRAY['DPIA','AIPD','analyse impact','risque élevé'],
   '[{"code":"35","source":"RGPD"}]'::jsonb,
   'DPIA obligatoire pour traitements à risque élevé.'),
  ('rgpd_demande_droits',            'Réponse à demande d''exercice de droits',    'rgpd',        'medium',   false,false,
   ARRAY['droit accès','effacement','portabilité','opposition'],
   '[{"code":"15","source":"RGPD"},{"code":"17","source":"RGPD"}]'::jsonb,
   'Réponse sous 1 mois (extensible 2 mois) — refus motivé possible.'),

  -- Fiscal
  ('fis_reclamation',                'Réclamation fiscale contentieuse',           'fiscal',      'high',     true, true,
   ARRAY['réclamation','contentieux fiscal','dégrèvement'],
   '[{"code":"L190","source":"Livre des procédures fiscales"}]'::jsonb,
   'Réclamation préalable obligatoire avant saisine du tribunal administratif.'),
  ('fis_redressement',               'Réponse à proposition de rectification',     'fiscal',      'critical', true, true,
   ARRAY['redressement','proposition rectification','vérification'],
   '[{"code":"L57","source":"Livre des procédures fiscales"}]'::jsonb,
   'Réponse sous 30 jours — silence = acceptation tacite des rehauts.'),

  -- Contentieux
  ('cnt_assignation',                'Assignation devant juridiction',             'contentieux', 'critical', true, true,
   ARRAY['assignation','citation','introduction instance'],
   '[{"code":"54","source":"Code de procédure civile"}]'::jsonb,
   'Acte d''huissier — formalisme strict, conséquences procédurales lourdes.'),
  ('cnt_conclusions',                'Dépôt de conclusions',                       'contentieux', 'critical', true, true,
   ARRAY['conclusions','écritures','plaidoirie'],
   '[{"code":"768","source":"Code de procédure civile"}]'::jsonb,
   'Conclusions structurées — moyens de droit et de fait, prétentions chiffrées.'),
  ('cnt_appel',                      'Déclaration d''appel',                       'contentieux', 'critical', true, true,
   ARRAY['appel','recours','RPVA'],
   '[{"code":"901","source":"Code de procédure civile"}]'::jsonb,
   'Délai 1 mois (15 jours en référé) — formalisme RPVA strict.'),

  -- Contrats
  ('ctr_avenant_majeur',             'Avenant modifiant un élément essentiel',     'contrats',    'high',     true, false,
   ARRAY['avenant','modification contrat','salaire','horaires'],
   '[{"code":"1193","source":"Code civil"}]'::jsonb,
   'Avenant essentiel — accord exprès du cocontractant requis.'),
  ('ctr_resiliation_faute',          'Résiliation pour faute',                     'contrats',    'high',     true, true,
   ARRAY['résiliation faute','résolution','clause résolutoire'],
   '[{"code":"1224","source":"Code civil"},{"code":"1225","source":"Code civil"}]'::jsonb,
   'Résolution pour inexécution — mise en demeure préalable nécessaire.'),

  -- Administratif
  ('adm_recours_hierarchique',       'Recours hiérarchique / gracieux',            'administratif','medium',  false,false,
   ARRAY['recours','gracieux','hiérarchique','REP'],
   '[{"code":"R421-1","source":"Code de justice administrative"}]'::jsonb,
   'Recours administratif préalable — proroge le délai contentieux.')
ON CONFLICT (action_key) DO NOTHING;
